server {
    listen 80;
    server_name localhost; # Puedes cambiarlo a tu dominio si lo tienes

    # Directorio raíz de tu aplicación Laravel (la carpeta 'public')
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html index.htm;

    charset utf-8;

    # Regla para manejar URLs amigables de Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bloquear acceso a archivos sensibles
    location ~ /\.env {
        deny all;
    }

    # Configuración para procesar archivos PHP con PHP-FPM
    location ~ \.php$ {
        # fastcgi_pass debe apuntar a la dirección y puerto de PHP-FPM
        # Dentro de la misma imagen, es 127.0.0.1:9000
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params; # Incluye parámetros FastCGI estándar
    }

    # Bloquear acceso a archivos ocultos (excepto .well-known para Let's Encrypt)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Manejo de errores
    error_page 404 /index.php; # Redirige 404 a Laravel para rutas no encontradas
}