[supervisord]
nodaemon=true ; Ejecuta supervisor en primer plano, esencial para Docker

; --- Configuración para Nginx ---
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" ; Inicia Nginx y lo mantiene en primer plano
autostart=true                          ; Inicia automáticamente al arrancar Supervisor
autorestart=true                        ; Reinicia automáticamente si falla
startretries=10                         ; Número de intentos de reinicio antes de fallar
stdout_logfile=/dev/stdout              ; Redirige la salida estándar de Nginx a los logs de Docker
stdout_logfile_maxbytes=0               ; Sin límite de tamaño de log
stderr_logfile=/dev/stderr              ; Redirige la salida de error estándar de Nginx a los logs de Docker
stderr_logfile_maxbytes=0               ; Sin límite de tamaño de log

; --- Configuración para PHP-FPM ---
[program:php-fpm]
command=/usr/local/sbin/php-fpm -F      ; Inicia PHP-FPM y lo mantiene en primer plano
autostart=true                          ; Inicia automáticamente al arrancar Supervisor
autorestart=true                        ; Reinicia automáticamente si falla
startretries=10                         ; Número de intentos de reinicio antes de fallar
stdout_logfile=/dev/stdout              ; Redirige la salida estándar de PHP-FPM a los logs de Docker
stdout_logfile_maxbytes=0               ; Sin límite de tamaño de log
stderr_logfile=/dev/stderr              ; Redirige la salida de error estándar de PHP-FPM a los logs de Docker
stderr_logfile_maxbytes=0               ; Sin límite de tamaño de log